version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3-alpine"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
    - "127.0.0.1:15672:15672"
    - "127.0.0.1:4369:4369"
    - "127.0.0.1:5672:5672"
    - "127.0.0.1:25672:25672"
